global:
  smtp_from: prometheus@localhost
  smtp_smarthost: smtp.localhost

route:
  repeat_interval: 3h
  receiver: team-emails

receivers:
- name: 'team-emails'
  email_configs:
  - to: 'team-emails@localhost'
