global:
  scrape_interval: 1m
  scrape_timeout: 15s
  evaluation_interval: 1m
  external_labels:
    monitor: 'miso-prometheus'
rule_files:
  - "alert.rules"
scrape_configs:
  - job_name: 'prometheus'
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9090','cadvisor:8080', 'node-exporter:9100']
  - job_name: 'pushgateway'
    honor_labels: true
    scrape_interval: 30s
    static_configs:
        - targets: ['pushgateway:9091']
remote_write:
  - url: http://chronix-ingester:8080/ingest
